services:
  - type: web
    name: warehouse-wms-api
    runtime: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: warehouse-db
          property: connectionString
      - key: PORT
        value: 10000
    
databases:
  - name: warehouse-db
    region: frankfurt
    plan: free
    databaseName: warehouse_wms
    user: warehouse_user
