services:
  - type: web
    name: warehouse-wms-api
    runtime: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: warehouse-db
          property: connectionString
    
databases:
  - name: warehouse-db
    databaseName: warehouse_wms
    user: warehouse_user
